### PR TITLE
fix endian detection to be portable to all gcc archs

### PR DESCRIPTION
**Pull request by basilgello**
Fixes Debia build regression

### CODE REVIEW

**Comment by basilgello** [comment]
@CastagnaIT @glennguy Please merge this and tag the new IA!

**Comment by CastagnaIT** [comment]
it is possible to merge but i ask
can you consider doing an upstream PR?
or is it something strictly related to kodi?

**Comment by basilgello** [comment]
@CastagnaIT No it is upstreamable. I will upstream it today

**Comment by basilgello** [comment]
@CastagnaIT Upstream merged this patch. Do we want to wait for a tag or merge here first?

**Comment by CastagnaIT** [comment]
i see that the commit hash its not the same, please take the same commit of upstream
so when we will rebase for the next bento release we are sure that this commit will be ignored

i think that we can wait to create a new tag release until just before Kodi RC1 will be released
so if there are other changes in the meantime they will be included without make a lot of releases

**Comment by basilgello** [comment]
@CastagnaIT I rebased the PR but I still can not have the same commit hash :(

**Comment by CastagnaIT** [comment]
i will take a look on next days

**Pull request merged**
